title: Git Docs
description: using just-the-docs
theme: just-the-docs
url: https://douglasshelby.github.io/docs
color_scheme: dark

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"